### ISSUE TITLE
Incompatible with Link's Awakening Redux

### ISSUE THREAD

**Issue by FedericoMz** [cphartman/super-awakening#2]
First of all, this is a great hack! Thank you for your hard work.

Unfortunately, it doesn't play nice with _[Link's Awakening Redux](https://github.com/ShadowOne333/Links-Awakening-Redux)_, the _other_ hack with key QoL improvements.

The game crashes at the beginning when patching Super and then Redux. It seems to work with Redux and then Super, but it freezes when Link gets the sword (which... turns into a shield).

**Comment by cphartman** [comment]
Thanks for testing and the feedback!  This wasn't tested with other gameplay patches.  It will probably not work with any of them because of the inventory changes in this hack.  I'll take a look at the Redux repo and see if there are ways to make it compatible or port over some of those QoL improvements.  I would like to eventually release some of these changes as separate patches that will work with vanilla/redux/ladxr, but I haven't prioritized that work at all.

**Comment by cphartman** [comment]
What emulator and base rom hash were you using?

**Comment by cphartman** [comment]
Release 1.1.3 fixes the issues where the sword pickup turns into a shield and the game locks.

**Comment by cphartman** [comment]
Making this compatible with Redux is not going to be prioritized right now, but I'll investigate this for v2.  If you are still getting the soft-lock with just the Super Awakening patch after 1.13, feel free to open another issue.
