### ISSUE TITLE
Missing DX Color Palette

### ISSUE THREAD

**Issue by seajaysec** [cphartman/super-awakening#3]
First of all, this project is brilliant and incredibly clever. Nice work. I didn't see it mentioned in the docs but may have missed it - is there no way to support the DX color palette in this hack? The green shades do look nice but I have nostalgia for the colors they used.

Also, how do you save? The usual button combo doesn't seem to be working. Did that change in the input reshuffling?

**Comment by cphartman** [comment]
Glad you are enjoying it!

>  is there no way to support the DX color palette in this hack?

Support for color pallets is very limited, but it does work in BGB with the following settings:
* Set Emulated System to `SGB + GBC`
* Set your `X`/`Y`/`L`/`R` button inputs on your controller to `A`/`B`/`Left`/`Right` on joypad1

Color with `Super Game Boy` has very limited support because it was never available on the original `Super Game Boy`.  It's a custom feature some emulators like `BGB` and `mGBA` implemented, but was never available on real Nintendo hardware.  `BGB` is the only emulator I found that supports both `SGB+GBC` and the player 2 inputs.  If you find any others I'll add it to the [compatibility list](https://github.com/cphartman/super-awakening/tree/main/docs/super-awakening#system-compatibility).

> Also, how do you save? The usual button combo doesn't seem to be working. Did that change in the input reshuffling?

Saving is now `A/X/Start/Select` or `B/Y/Start/Select`.  I'll add a note to the readme!

**Comment by seajaysec** [comment]
Right on, thanks that works for saving and makes sense about the palette!

**Comment by cphartman** [comment]
Restored support for `A/B/Start/Select` save in 1.1.4.  The other ways (`A/X/Start/Select` and `B/Y/Start/Select`) will continue to work too.
